# skip verification for this object
skipObjects:
- kind: ConfigMap
  name: kube-root-ca.crt

# ignore `data.key2` field changes in `sample-cm` ConfigMap
ignoreFields:
  - objects:
    - kind: ConfigMap
      name: sample-cm
    fields:
    - data.key2

# only a signer with this name is allowed (in case of keyless)
signers:
- sample-signer@example.com
