name: SLSA go releaser
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  args: 
    runs-on: ubuntu-latest
    outputs:
      ldflags: "{{ .Env.LDFLAGS }}"
    steps:
      - id: checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2.3.4
        with:
          fetch-depth: 0

  # Trusted builder.
  build-linux-amd64:
    permissions:
      id-token: write # To sign the provenance.
      contents: write # To upload assets to release.
      actions: read # To read the workflow path.
    needs: args
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.2.0
    with:
      config-file: .slsa-goreleaser-linux-amd64.yml
      go-version: 1.18
      evaluated-envs: "VERSION_LDFLAGS:${{needs.args.outputs.ldflags}}"
      #compile-builder: true # See github.com/slsa-framework/slsa-github-generator/issues/942